feat: add stats_tags
jambonz/helm-charts pull request #26
Opened 2023-04-05 11:38 UTC by xquanluu

2023-04-05 19:00 UTC, davehorton requested changes

2023-04-05 19:00 UTC, davehorton commented on templates/api-server-deployment.yaml
> +            - name: K8S_POD_NAME
the env K8S_POD_NAME must appear above another env that wants to interpolate that value, so it must come before STATS_TAGS.  This applies to each of these files where it appears.

2023-04-05 23:36 UTC, xquanluu commented on templates/api-server-deployment.yaml
> +              value: "host:$(K8S_POD_NAME)"
change to pod

2023-04-06 00:23 UTC, davehorton approved these changes

2023-04-06 00:23 UTC, merged